version: "3.8"
services:
  api:
    container_name: {{cookiecutter.repo_name}}-api-${ENVIRONMENT}
    build:
      dockerfile: ./backend/Dockerfile
      context: ./
    env_file:
      - .env
    volumes:
      - static:/code/static
      - attachments:/code/attachments
    image: {{cookiecutter.repo_name}}-api-${ENVIRONMENT}
  nginx:
    container_name: {{cookiecutter.repo_name}}-nginx-${ENVIRONMENT}
    build:
      dockerfile: ./nginx/Dockerfile
      context: ./
      args:
        - API_URL
        - ENVIRONMENT
    ports:
      - "${SERVICE_PORT}:80"
    restart: always
    env_file:
      - .env
    volumes:
      - static:/static
      - attachments:/attachments
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - api
volumes:
  static:
  attachments:
